import { useState, useRef, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { Play, Volume2, VolumeX, Loader2 } from 'lucide-react';
import { cn } from '@/utils/cn';
import { useAuth } from '../../contexts/AuthContext';
import { api } from '../../services/api';
import { toChatUrl } from '@/utils/chatUrl';

// Placeholder data for 12 characters
// In a real application, these URLs would be replaced by the assets generated by Nano Banana and Veo3.1
const VIDEO_CHARACTERS = [
  {
    id: 'vc1',
    name: 'Roxanne',
    age: 24,
    desc: 'Daring & Bold',
    storyTitle: 'Daring & Bold',
    storyDescription: 'Daring & Bold',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    video: '' 
  },
  {
    id: 'vc2',
    name: 'Tiffany',
    age: 22,
    desc: 'Playful Soul',
    storyTitle: 'Playful Soul',
    storyDescription: 'Playful Soul',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    video: ''
  },
  {
    id: 'vc3',
    name: 'Carmen',
    age: 26,
    desc: 'Sultry Vibes',
    storyTitle: 'Sultry Vibes',
    storyDescription: 'Sultry Vibes',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
    video: ''
  },
  {
    id: 'vc4',
    name: 'Sasha',
    age: 23,
    desc: 'Fierce Energy',
    storyTitle: 'Fierce Energy',
    storyDescription: 'Fierce Energy',
    image: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80',
    video: ''
  },
  {
    id: 'vc5',
    name: 'Nina',
    age: 21,
    desc: 'Sweetheart',
    storyTitle: 'Sweetheart',
    storyDescription: 'Sweetheart',
    image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=600&q=80',
    video: ''
  },
  {
    id: 'vc6',
    name: 'Bella',
    age: 25,
    desc: 'Elegant',
    storyTitle: 'Elegant',
    storyDescription: 'Elegant',
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&q=80',
    video: ''
  },
  {
    id: 'vc7',
    name: 'Zoe',
    age: 20,
    desc: 'Fun Loving',
    storyTitle: 'Fun Loving',
    storyDescription: 'Fun Loving',
    image: 'https://images.unsplash.com/photo-1524250502761-1f96b3609b3e?auto=format&fit=crop&w=600&q=80',
    video: ''
  },
  {
    id: 'vc8',
    name: 'Lola',
    age: 27,
    desc: 'Wild Heart',
    storyTitle: 'Wild Heart',
    storyDescription: 'Wild Heart',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    video: ''
  },
  {
    id: 'vc9',
    name: 'Vicky',
    age: 22,
    desc: 'Sporty Chic',
    storyTitle: 'Sporty Chic',
    storyDescription: 'Sporty Chic',
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=600&q=80',
    video: ''
  },
  {
    id: 'vc10',
    name: 'Mila',
    age: 24,
    desc: 'Charming',
    storyTitle: 'Charming',
    storyDescription: 'Charming',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    video: ''
  },
  {
    id: 'vc11',
    name: 'Eva',
    age: 28,
    desc: 'Classic Beauty',
    storyTitle: 'Classic Beauty',
    storyDescription: 'Classic Beauty',
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=80',
    video: ''
  },
  {
    id: 'vc12',
    name: 'Cleo',
    age: 25,
    desc: 'Exotic Charm',
    storyTitle: 'Exotic Charm',
    storyDescription: 'Exotic Charm',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=600&q=80',
    video: ''
  }
];



export function VideoCharacterGrid({ characters = VIDEO_CHARACTERS }: { characters?: any[] }) {
  const navigate = useNavigate();
  const { isAuthenticated } = useAuth();
  const [activeVideo, setActiveVideo] = useState<string | null>(null);
  const [muted, setMuted] = useState(true);
  const [loadingId, setLoadingId] = useState<string | null>(null);
  const videoRefs = useRef<{ [key: string]: HTMLVideoElement }>({});

  const displayCharacters = useMemo(() => {
    if (!Array.isArray(characters)) return [];
    return characters.map((char) => {
      let videoSrc = char.video;
      // If videos list exists and has items, pick a random one
      if (char.videos && Array.isArray(char.videos) && char.videos.length > 0) {
        const randomIndex = Math.floor(Math.random() * char.videos.length);
        videoSrc = char.videos[randomIndex];
      }
      
      return {
        ...char,
        displayVideo: videoSrc || null
      };
    });
  }, [characters]);

  const handleChat = async (e: React.MouseEvent, char: any) => {
    e.stopPropagation();

    if (!char.id) {
      // If authenticated, go to chat, otherwise go to register
      navigate(isAuthenticated ? '/chat' : '/register');
      return;
    }

    // Guest mode: Navigate directly to guest chat
    if (!isAuthenticated) {
      navigate(`${toChatUrl(char)}?mode=guest`);
      return;
    }

    // Authenticated: Copy official character and navigate
    try {
      setLoadingId(char.id);
      const response = await api.post(`/chat/chat_now_official/${char.id}`);
      const userCharacterId = response.data?.character_id;

      if (!userCharacterId) {
        throw new Error('Failed to get character ID from response');
      }

      // Navigate with the user's character copy ID (may not have slug yet)
      navigate(`/chat?character=${userCharacterId}&ready=1`);
    } catch (error) {
      console.error('Failed to start chat:', error);
      alert('Failed to start chat. Please try again.');
    } finally {
      setLoadingId(null);
    }
  };

  const handleMouseEnter = (id: string) => {
    const char = displayCharacters.find((item) => item.id === id);
    if (!char?.displayVideo) return;

    setActiveVideo(id);
    if (videoRefs.current[id]) {
      videoRefs.current[id].play().catch(() => {
        // Autoplay might be blocked
      });
    }
  };

  const handleMouseLeave = (id: string) => {
    setActiveVideo(null);
    if (videoRefs.current[id]) {
      videoRefs.current[id].pause();
      videoRefs.current[id].currentTime = 0;
    }
  };

  const toggleMute = (e: React.MouseEvent) => {
    e.stopPropagation();
    setMuted(!muted);
  };

  return (
    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 md:gap-6">
      {displayCharacters.map((char) => (
        <div 
          key={char.id}
          className="group relative aspect-[3/4] rounded-xl overflow-hidden cursor-pointer"
          onMouseEnter={() => handleMouseEnter(char.id)}
          onMouseLeave={() => handleMouseLeave(char.id)}
          onClick={(e) => handleChat(e, char)}
        >
          {/* Static Image */}
          <div className={cn(
            "absolute inset-0 transition-opacity duration-500",
            activeVideo === char.id ? "opacity-0" : "opacity-100"
          )}>
            <img 
              src={char.image} 
              alt={char.name}
              className="w-full h-full object-cover"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent"></div>
          </div>

          {/* Video Layer */}
          {char.displayVideo && (
            <div className={cn(
              "absolute inset-0 transition-opacity duration-500 bg-black",
              activeVideo === char.id ? "opacity-100" : "opacity-0"
            )}>
              <video
                ref={el => { if (el) videoRefs.current[char.id] = el }}
                src={char.displayVideo}
                className="w-full h-full object-cover"
                loop
                muted={muted}
                playsInline
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent"></div>
              
              <button
                onClick={toggleMute}
                className="absolute top-3 right-3 p-2 rounded-full bg-black/50 hover:bg-black/70 text-white transition-colors"
              >
                {muted ? <VolumeX size={16} /> : <Volume2 size={16} />}
              </button>
            </div>
          )}

          {/* Info Overlay */}
          <div className="absolute bottom-0 left-0 right-0 p-4 transform transition-transform duration-300 group-hover:translate-y-0 translate-y-2">
            <div className="space-y-2">
              <h3 className="text-lg font-bold text-white">{char.name}</h3>
              <p className="text-xs text-zinc-200/90 line-clamp-3 leading-relaxed transition-opacity duration-200 group-hover:opacity-0">
                {char.desc || 'AI Companion'}
              </p>
              <div className="pointer-events-none absolute left-4 right-4 top-11 opacity-0 transition-opacity duration-200 group-hover:opacity-100">
                {char.storyTitle && (
                  <p className="text-[11px] uppercase tracking-wide text-primary-300/90">
                    {char.storyTitle}
                  </p>
                )}
                <p className="mt-1 text-xs text-zinc-100 line-clamp-4 leading-relaxed">
                  {char.storyDescription || 'No opening script available yet.'}
                </p>
              </div>
            </div>

            <div className="mt-3 flex items-center justify-end text-xs text-zinc-400">
              <div className="flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300 delay-100">
                {loadingId === char.id ? (
                  <Loader2 size={12} className="text-primary-400 animate-spin" />
                ) : (
                  <Play size={12} className="text-primary-400 fill-primary-400" />
                )}
                <span className="text-xs font-medium text-primary-400">
                  {loadingId === char.id ? 'Loading...' : 'Chat Now'}
                </span>
              </div>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}
