import { useState, useEffect, useCallback } from 'react';
import { useWizard } from '@/contexts/CharacterWizardContext';
import { WizardStep } from '../WizardStep';
import { Input, Button } from '@/components/common';
import { Sparkles, Image as ImageIcon, Loader2 } from 'lucide-react';
import { api } from '@/services/api';
import { normalizeTaskStatus } from '@/utils/taskStatus';

const raceOptions: { value: string; label: string }[] = [
  { value: 'white race', label: 'White' },
  { value: 'black race', label: 'Black' },
  { value: 'yellow race', label: 'Asian' },
];

interface Step9ConfirmProps {
  avatarGenerationCount: number;
  onAvatarGenerated: () => void;
}

const AVATAR_POLL_INTERVAL_MS = 2500;
const AVATAR_POLL_MAX_ATTEMPTS = 120;

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => {
    window.setTimeout(resolve, ms);
  });
}

function uniqueUrls(urls: string[]): string[] {
  return Array.from(new Set(urls.filter(Boolean)));
}

function extractImageUrls(payload: unknown): string[] {
  const data = (payload ?? {}) as Record<string, unknown>;
  const result = (data.result ?? {}) as Record<string, unknown>;

  const imageUrls = Array.isArray(data.image_urls)
    ? data.image_urls
    : Array.isArray(result.image_urls)
      ? result.image_urls
      : [];
  if (imageUrls.length > 0) {
    return uniqueUrls(imageUrls.map((url) => String(url)));
  }

  const resultData = result.data;
  if (Array.isArray(resultData)) {
    return uniqueUrls(resultData.map((url) => String(url)));
  }
  if (typeof resultData === 'string' && resultData.trim()) {
    return [resultData.trim()];
  }

  const imageUrl = data.image_url || result.image_url;
  if (typeof imageUrl === 'string' && imageUrl.trim()) {
    return [imageUrl.trim()];
  }

  return [];
}

function extractTaskIds(payload: unknown): string[] {
  const data = (payload ?? {}) as Record<string, unknown>;
  const result = (data.result ?? {}) as Record<string, unknown>;
  const taskIds: string[] = [];

  const primaryId = data.task_id || data.id;
  if (typeof primaryId === 'string' && primaryId.trim()) {
    taskIds.push(primaryId.trim());
  }
  const resultPrimaryId = result.task_id || result.id;
  if (typeof resultPrimaryId === 'string' && resultPrimaryId.trim()) {
    taskIds.push(resultPrimaryId.trim());
  }

  if (Array.isArray(data.task_ids)) {
    taskIds.push(
      ...data.task_ids
        .filter((taskId): taskId is string => typeof taskId === 'string' && taskId.trim().length > 0)
        .map((taskId) => taskId.trim())
    );
  }
  if (Array.isArray(result.task_ids)) {
    taskIds.push(
      ...result.task_ids
        .filter((taskId): taskId is string => typeof taskId === 'string' && taskId.trim().length > 0)
        .map((taskId) => taskId.trim())
    );
  }

  if (Array.isArray(data.tasks)) {
    for (const task of data.tasks) {
      if (typeof task === 'string' && task.trim()) {
        taskIds.push(task.trim());
      } else if (task && typeof task === 'object') {
        const taskRecord = task as Record<string, unknown>;
        const taskId = taskRecord.task_id || taskRecord.id;
        if (typeof taskId === 'string' && taskId.trim()) {
          taskIds.push(taskId.trim());
        }
      }
    }
  }

  return uniqueUrls(taskIds);
}

export function Step9Confirm({ avatarGenerationCount, onAvatarGenerated }: Step9ConfirmProps) {
  const { characterData, updateNestedField, updateField } = useWizard();
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedOptions, setGeneratedOptions] = useState<string[]>([]);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const regenerateCount = Math.max(0, avatarGenerationCount - 1);
  const regenerateLimitReached = regenerateCount >= 2;
  const hasGeneratedBefore = avatarGenerationCount > 0 || !!characterData.avatarUrl;

  const handleAgeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    const age = value === '' ? undefined : parseInt(value, 10);
    updateNestedField('identity.age', age);
  };

  const isAgeValid =
    characterData.identity.age !== undefined &&
    characterData.identity.age >= 18 &&
    characterData.identity.age <= 99;

  const pollTaskForImages = useCallback(async (taskId: string): Promise<string[]> => {
    for (let attempt = 0; attempt < AVATAR_POLL_MAX_ATTEMPTS; attempt += 1) {
      const response = await api.get(`/images/tasks/${taskId}`);
      const statusData = response.data as Record<string, unknown>;
      const status = normalizeTaskStatus(
        typeof statusData.status === 'string'
          ? statusData.status
          : typeof statusData.raw_status === 'string'
            ? statusData.raw_status
            : undefined
      );

      if (status === 'succeeded') {
        return extractImageUrls(statusData);
      }
      if (status === 'failed') {
        throw new Error(`Avatar task failed: ${taskId}`);
      }

      await delay(AVATAR_POLL_INTERVAL_MS);
    }

    throw new Error(`Avatar task polling timeout: ${taskId}`);
  }, []);

  const handleGenerateAvatar = useCallback(async () => {
    if (hasGeneratedBefore && regenerateLimitReached) {
      return;
    }

    setIsGenerating(true);
    try {
      const promptParts = [
        'Best quality, masterpiece',
        characterData.gender === 'Male' ? '1boy, male' : '1girl, female',
        characterData.style || 'Realistic',
        characterData.identity.age ? `${characterData.identity.age} years old` : '',
        characterData.identity.race || '',
        characterData.appearance.bodyType,
        characterData.appearance.skinTone ? `${characterData.appearance.skinTone} skin` : '',
        characterData.hair.color ? `${characterData.hair.color} hair` : '',
        characterData.hair.style ? `${characterData.hair.style} hair` : '',
        characterData.face.eyeColor ? `${characterData.face.eyeColor} eyes` : '',
        characterData.face.lipColor ? `${characterData.face.lipColor} lips` : '',
        characterData.personality.tags.length > 0 ? `${characterData.personality.tags.join(', ')} expression` : '',
        characterData.outfit.style ? `wearing ${characterData.outfit.style}` : '',
        characterData.outfit.description,
        'looking at viewer, portrait',
      ];
      const prompt = promptParts.filter(Boolean).join(', ');

      const response = await api.post('/images/generate-batch', { prompt, count: 2 });
      const initialImageUrls = extractImageUrls(response.data);
      const taskIds = extractTaskIds(response.data);

      const polledImageUrls: string[] = [];
      if (taskIds.length > 0) {
        const taskResults = await Promise.allSettled(taskIds.map((taskId) => pollTaskForImages(taskId)));
        for (const result of taskResults) {
          if (result.status === 'fulfilled') {
            polledImageUrls.push(...result.value);
          } else {
            console.error('Avatar task polling failed', result.reason);
          }
        }
      }

      const finalImageUrls = uniqueUrls([...initialImageUrls, ...polledImageUrls]);

      if (finalImageUrls.length > 0) {
        setGeneratedOptions((prev) => uniqueUrls([...prev, ...finalImageUrls]));
        onAvatarGenerated();
        if (!characterData.avatarUrl) {
          updateField('avatarUrl', finalImageUrls[0]);
        }
      }
    } catch (error) {
      console.error('Failed to generate avatar', error);
    } finally {
      setIsGenerating(false);
    }
  }, [
    characterData.gender,
    characterData.style,
    characterData.identity.age,
    characterData.identity.race,
    characterData.appearance.bodyType,
    characterData.appearance.skinTone,
    characterData.hair.color,
    characterData.hair.style,
    characterData.face.eyeColor,
    characterData.face.lipColor,
    characterData.personality.tags,
    characterData.outfit.style,
    characterData.outfit.description,
    characterData.avatarUrl,
    hasGeneratedBefore,
    regenerateLimitReached,
    onAvatarGenerated,
    pollTaskForImages,
    updateField,
  ]);

  useEffect(() => {
    if (!characterData.avatarUrl && !isGenerating && !hasAutoGenerated) {
      setHasAutoGenerated(true);
      handleGenerateAvatar();
    }
  }, [characterData.avatarUrl, isGenerating, hasAutoGenerated, handleGenerateAvatar]);

  const selectAvatar = (url: string) => {
    updateField('avatarUrl', url);
  };

  return (
    <WizardStep
      title="Confirm and Finish"
      description="Name your character and generate a final avatar"
    >
      <div className="space-y-8">
        <div>
          <Input
            label="Character Name"
            placeholder="e.g., Emma, Sophia, Olivia"
            value={characterData.identity.firstName || ''}
            onChange={(e) => updateNestedField('identity.firstName', e.target.value)}
            helperText="Choose a name that fits your character"
          />
        </div>

        <div>
          <Input
            label="Age"
            type="number"
            min={18}
            max={99}
            placeholder="18-99"
            value={characterData.identity.age?.toString() || ''}
            onChange={handleAgeChange}
            error={
              characterData.identity.age !== undefined && !isAgeValid
                ? 'Age must be between 18 and 99'
                : undefined
            }
            helperText="Character must be 18 or older"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-zinc-300 mb-2">
            Race (Optional)
          </label>
          <select
            value={characterData.identity.race || ''}
            onChange={(e) => updateNestedField('identity.race', e.target.value || undefined)}
            className="w-full px-4 py-3 bg-white/5 border border-white/10 rounded-lg text-black focus:outline-none focus:ring-2 focus:ring-primary-500"
          >
            <option value="" className="text-black">Select race (optional)</option>
            {raceOptions.map((option) => (
              <option key={option.value} value={option.value} className="text-black">
                {option.label}
              </option>
            ))}
          </select>
          <p className="text-xs text-zinc-500 mt-1">
            This helps with generating accurate character images.
          </p>
        </div>

        <div>
          <div className="flex items-center gap-2 mb-4">
            <ImageIcon size={20} className="text-primary-500" />
            <h3 className="text-lg font-semibold">Avatar</h3>
          </div>

          <div className="flex flex-col items-center gap-4 p-6 rounded-lg glass-effect border border-white/10">
            {generatedOptions.length > 0 ? (
              <div className="grid grid-cols-3 gap-4 w-full">
                {generatedOptions.map((url, index) => (
                  <div
                    key={index}
                    onClick={() => selectAvatar(url)}
                    className={`relative aspect-square rounded-xl overflow-hidden cursor-pointer transition-all ${
                      characterData.avatarUrl === url
                        ? 'border-4 border-primary-500 scale-105 shadow-lg shadow-primary-500/20'
                        : 'border border-white/10 hover:border-white/30 hover:scale-105'
                    }`}
                  >
                    <img src={url} alt={`Option ${index + 1}`} className="w-full h-full object-cover" />
                    {characterData.avatarUrl === url && (
                      <div className="absolute top-2 right-2 bg-primary-500 text-white rounded-full p-1">
                        <Sparkles size={12} />
                      </div>
                    )}
                  </div>
                ))}
              </div>
            ) : characterData.avatarUrl ? (
              <div className="relative w-64 h-64 rounded-xl overflow-hidden border-2 border-primary-500">
                <img src={characterData.avatarUrl} alt="Generated Avatar" className="w-full h-full object-cover" />
              </div>
            ) : (
              <div className="w-64 h-64 rounded-xl bg-white/5 flex items-center justify-center border border-white/10">
                <p className="text-zinc-500 text-sm">No avatar generated</p>
              </div>
            )}

            <Button
              onClick={handleGenerateAvatar}
              disabled={isGenerating || (hasGeneratedBefore && regenerateLimitReached)}
              className="w-full max-w-xs flex items-center justify-center gap-2 mt-4"
            >
              {isGenerating ? (
                <>
                  <Loader2 size={18} className="animate-spin" />
                  Generating 2 Options...
                </>
              ) : (
                <>
                  <Sparkles size={18} />
                  {hasGeneratedBefore ? `Regenerate Avatars (${regenerateCount}/2)` : 'Generate Avatars'}
                </>
              )}
            </Button>
            {hasGeneratedBefore && (
              <p className="text-xs text-zinc-400 text-center">
                Regenerate limit: {regenerateCount}/2 used per character creation.
              </p>
            )}
            {hasGeneratedBefore && regenerateLimitReached && (
              <p className="text-xs text-amber-400 text-center">
                You have reached the maximum regenerate attempts for this character.
              </p>
            )}
          </div>
        </div>

        {characterData.identity.firstName && isAgeValid && (
          <div className="mt-8 p-6 rounded-lg glass-effect border border-primary-500/20">
            <h4 className="text-sm font-semibold text-primary-500 mb-3">
              Character Preview
            </h4>
            <div className="space-y-2 text-sm">
              <p>
                <span className="text-zinc-400">Name:</span>{' '}
                <span className="text-white font-medium">
                  {characterData.identity.firstName}, {characterData.identity.age}
                </span>
              </p>
              <p>
                <span className="text-zinc-400">Style:</span>{' '}
                <span className="text-white">{characterData.style}</span>
              </p>
              <p>
                <span className="text-zinc-400">Personality:</span>{' '}
                <span className="text-white">
                  {characterData.personality.tags.join(', ')}
                </span>
              </p>
              <p>
                <span className="text-zinc-400">Relationship:</span>{' '}
                <span className="text-white">
                  {characterData.personality.relationship}
                </span>
              </p>
              {characterData.background.profession && (
                <p>
                  <span className="text-zinc-400">Profession:</span>{' '}
                  <span className="text-white">
                    {characterData.background.profession}
                  </span>
                </p>
              )}
            </div>
          </div>
        )}

        <div className="text-center p-6 rounded-lg bg-gradient-primary/10 border border-primary-500/30">
          <p className="text-zinc-200">
            You are all set. Click "Create Character" to bring your AI companion to life.
          </p>
        </div>
      </div>
    </WizardStep>
  );
}
